# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    extraModprobeConfig = ''
      options brcmfmac feature_disable=0x2000
    '';
    kernelPackages = pkgs.linuxKernel.packages.linux_rpi4;
    loader = {
      # Enables the generation of /boot/extlinux/extlinux.conf
      generic-extlinux-compatible.enable = true;
      # Use the extlinux boot loader. (NixOS wants to enable GRUB by default)
      grub.enable = false;
    };
    initrd = {
      availableKernelModules = ["xhci_pci" "usbhid" "usb_storage"];
      kernelModules = [];
    };
    kernelModules = [];
    extraModulePackages = [];
    supportedFilesystems.zfs = lib.mkForce false;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS_SD";
    fsType = "ext4";
    options = ["noatime"];
  };

  swapDevices = [];

  nixpkgs = {
    hostPlatform = lib.mkDefault "aarch64-linux";
    config = {
      allowUnfree = true;
    };
    overlays = [
      (final: super: {
        makeModulesClosure = x:
          super.makeModulesClosure (x // {allowMissing = true;});
      })
    ];
  };
}
